image:
  - Visual Studio 2022
  - Ubuntu
  - macOS

version: 3.4.0-b{build}

test: off

skip_commits:
  message: /noci .*/

build_script:
  - dotnet run  -f net6.0 -c Release --project test/FastExpressionCompiler.TestsRunner/FastExpressionCompiler.TestsRunner.csproj

for:
  - matrix:
      only:
        - image: Visual Studio 2022

    build_script:
      - build_with_packaging.bat

    artifacts:
      - path: .\.dist\*.nupkg
