image:
  - Visual Studio 2019
  - Ubuntu
  - macOS

version: 3.0.0-preview-01-b{build}

test: off

skip_commits:
  message: /skipci .*/

build_script:
  - dotnet run  -f netcoreapp3.1 -c Release -p test/FastExpressionCompiler.TestsRunner/FastExpressionCompiler.TestsRunner.csproj
  - dotnet test -f netcoreapp3.1 -c Release test/FastExpressionCompiler.IssueTests/FastExpressionCompiler.IssueTests.csproj
  - dotnet test -f netcoreapp3.1 -c Release test/FastExpressionCompiler.LightExpression.IssueTests/FastExpressionCompiler.LightExpression.IssueTests.csproj

for:
  - matrix:
      only:
        - image: Visual Studio 2019

    build_script:
      - dotnet build -c Release -v:m -p:DevMode=false
      - dotnet run  --no-build -c Release -p test/FastExpressionCompiler.TestsRunner/FastExpressionCompiler.TestsRunner.csproj
      - dotnet test --no-build -c Release -p:DevMode=false test/FastExpressionCompiler.IssueTests/FastExpressionCompiler.IssueTests.csproj
      - dotnet test --no-build -c Release -p:DevMode=false test/FastExpressionCompiler.LightExpression.IssueTests/FastExpressionCompiler.LightExpression.IssueTests.csproj

    artifacts:
      - path: .\.dist\*.nupkg
