image:
  - Visual Studio 2022
  - Ubuntu
  - macOS

version: 3.3.0-b{build}

test: off

skip_commits:
  message: /noci .*/

build_script:
  - dotnet run  -f netcoreapp3.1 -c Release -p test/FastExpressionCompiler.TestsRunner/FastExpressionCompiler.TestsRunner.csproj

for:
  - matrix:
      only:
        - image: Visual Studio 2022

    build_script:
      - build_with_packaging.bat

    artifacts:
      - path: .\.dist\*.nupkg
