image:
  - Visual Studio 2019
  - Ubuntu
  - macOS

version: 3.0.0-preview-01-b{build}

test: off

skip_commits:
  message: /skipci .*/

build_script:
  - dotnet run  -f netcoreapp3.1 -c Release -p test/FastExpressionCompiler.TestsRunner/FastExpressionCompiler.TestsRunner.csproj

for:
  - matrix:
      only:
        - image: Visual Studio 2019

    build_script:
      - dotnet build -c Release -v:m
      - dotnet run --no-build -c Release -p test/FastExpressionCompiler.TestsRunner/FastExpressionCompiler.TestsRunner.csproj
      - dotnet run --no-build -c Release -p test/FastExpressionCompiler.TestsRunner.Net472/FastExpressionCompiler.TestsRunner.Net472.csproj

    artifacts:
      - path: .\.dist\*.nupkg
